name: AccuKnox Juice Shop Container Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Juice Shop Docker image
        run: docker build -t juice-shop:latest .

      - name: List Docker images
        run: docker images

      - name: Run AccuKnox CSPM Scan
        uses: accuknox/container-scan-action@v1.0.1
        with:
          soft_fail: false
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          image_name: "juice-shop"
          tag: "latest"
          severity: "HIGH"
